ci: use VM with the installed tools and fallback otherwise
elastic/apm-agent-android pull request #274
Opened 2024-03-07 14:24 UTC by v1v

### What

* Support custom VM images that contain the JDK11, gradlew and the dependencies.
* Remove runtime installations - although support for a fallback.
* Use `.java-version` to store the current version based on major, as explained in https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#java-version-file
* Test the Release when merges on `main` with `dry-run=true`
* Run release if `dry-run=false` only to play safe.

### Why

* Stability and reliability.
* Faster builds.

### Test

2024-03-08 11:39 UTC, amannocci requested changes

2024-03-08 11:39 UTC, amannocci commented on .buildkite/hooks/pre-command
> +JAVA_VERSION=$(cat .java-version)
```suggestion
JAVA_VERSION=$(cat .java-version | xargs | tr -dc '[:print:]')
```

2024-03-08 11:39 UTC, amannocci commented on .buildkite/hooks/pre-command
> +ANDROID_HOME=$PWD/.android-sdk
```suggestion
ANDROID_HOME="${PWD}/.android-sdk"
```

2024-03-08 14:14 UTC, amannocci approved these changes

2024-03-11 09:03 UTC, LikeTheSalad approved these changes

2024-03-11 09:27 UTC, reakaleek approved these changes

2024-03-11 09:50 UTC, merged